### ISSUE TITLE
streaming examples

### ISSUE THREAD

**Issue by marclava** [Consti10/LiveVideo10ms#1]
How to stream a test video to the app? For example with FFmpeg? Here's what I tried (without success):
ffmpeg -re -i 1_reallyShort.mp4 -an -f rtp rtp://192.168.1.22:5600

**Comment by Consti10** [comment]
Hello,
You can use the following gstreamer command to stream an example video to FPV_VR / VideoExampe via rtph264 on port 5600:
`gst-launch-1.0 -v videotestsrc ! video/x-raw,framerate=120/1,width=1280,height=720 ! videoscale ! videoconvert ! x264enc key-int-max= 1 bitrate=5000 ! video/x-h264, profile=baseline ! rtph264pay ! udpsink host=192.168.137.47 port=5600`

**Comment by marclava** [comment]
The command you provided works. 

I was also able to play a file, using this command:
gst-launch-1.0 filesrc location=file.m4v ! queue ! qtdemux ! rtph264pay ! udpsink host=192.168.1.22 port=5600

But it works only if the file is encoded using the baseline profile (Baseline@3.1), and only after your test command is executed; is there something missing in my command to properly initiate the video stream, so the app can decode it no matter the encoding profile?

**Comment by Consti10** [comment]
Thanks for the command. If you find any other usefull pipelines, don't hesitate to share them here in this thread.
