### ISSUE TITLE
difference from gstreamer

### ISSUE THREAD

**Issue by Abu-Abdullah** [Consti10/LiveVideo10ms#4]
Hi,

this is just a question, today im using gstreamer in android to decode the RTP streaming. is there any value i will get using this library from using the standard gstreamer library. what would be the difference here.

thank you

**Comment by Consti10** [comment]
The main difference is that gstreamer is a big black box where latency is sometimes hard to measure and customization is also hard.

**Comment by Consti10** [comment]
If you want quick h264 and h265 decoding and use RTP (not rtsp) LiveVideo10ms is a good choice and should be plug and play.

**Comment by Abu-Abdullah** [comment]
thank you
